@SETLOCAL
@SET THIS=%0
@SET THIS_DIR=%~dp0

@ECHO THIS=%THIS%
@ECHO THIS_DIR=%THIS_DIR%

@SET PROJ_ROOT=%THIS_DIR%..\..\src\Tug.Server
@SET DOTNET_MONIK=
@REM  -f netcoreapp1.1

dotnet run -p %PROJ_ROOT% %DOTNET_MONIK% -- %* 

@ENDLOCAL
