@SETLOCAL
@SET THIS=%0
@SET THIS_DIR=%~dp0

@ECHO THIS=%THIS%
@ECHO THIS_DIR=%THIS_DIR%

@SET PROJ_ROOT=%THIS_DIR%..\..\src\Tug.Server
@SET PROJ_FILE=%PROJ_ROOT%\Tug.Server.csproj
@SET DOTNET_MONIK=-f net452

dotnet run -p %PROJ_FILE% %DOTNET_MONIK% -- %* 

@ENDLOCAL
